
package org.tinygroup.buildinfo.dao.inter.constant;

import org.tinygroup.buildinfo.dao.inter.pojo.BuildPubdemand;
import org.tinygroup.tinysqldsl.base.Column;
import org.tinygroup.tinysqldsl.base.Table;

/**
 * <!-- begin-user-doc --> 发布需求 * <!-- end-user-doc -->
 */
public class BuildPubdemandTable extends Table {

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public static final BuildPubdemandTable BUILD_PUBDEMAND_TABLE = new BuildPubdemandTable();

	/**
	 * <!-- begin-user-doc --> ID * <!-- end-user-doc -->
	 */
	public final Column ID = new Column(this, "id");
	/**
	 * <!-- begin-user-doc --> NAME * <!-- end-user-doc -->
	 */
	public final Column NAME = new Column(this, "name");
	/**
	 * <!-- begin-user-doc --> 客户电话 * <!-- end-user-doc -->
	 */
	public final Column PHONE = new Column(this, "phone");
	/**
	 * <!-- begin-user-doc --> 客户需求 * <!-- end-user-doc -->
	 */
	public final Column DEMAND = new Column(this, "demand");
	
	public final Column DEMAND_STATE = new Column(this, "demand_state");
	/**
	 * <!-- begin-user-doc --> 需求描述 * <!-- end-user-doc -->
	 */
	public final Column DEMAND_DESC = new Column(this, "demand_desc");
	/**
	 * <!-- begin-user-doc --> 顾问编号 * <!-- end-user-doc -->
	 */
	public final Column ADISVER_ID = new Column(this, "adisver_id");
	/**
	 * <!-- begin-user-doc --> 顾问姓名 * <!-- end-user-doc -->
	 */
	public final Column ADISVER_NAME = new Column(this, "adisver_name");
	
	public final Column PUB_TIME = new Column(this, "pub_time");
	
	public final Column UPDATE_TIME = new Column(this, "update_time");
	/**
	 * <!-- begin-user-doc --> 扩展字段1 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_1 = new Column(this, "ext_field_1");
	/**
	 * <!-- begin-user-doc --> 扩展字段2 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_2 = new Column(this, "ext_field_2");
	/**
	 * <!-- begin-user-doc --> 扩展字段3 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_3 = new Column(this, "ext_field_3");
	/**
	 * <!-- begin-user-doc --> 扩展字段4 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_4 = new Column(this, "ext_field_4");
	/**
	 * <!-- begin-user-doc --> 扩展字段5 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_5 = new Column(this, "ext_field_5");

	public BuildPubdemandTable() {
		super("build_pubdemand");
	}

	public BuildPubdemandTable(String schemaName) {
		super(schemaName, "build_pubdemand");
	}

	public BuildPubdemandTable(String schemaName, String alias) {
		super(schemaName, "build_pubdemand", alias);
	}

	public BuildPubdemandTable(String schemaName, String alias, boolean withAs) {
		super(schemaName, "build_pubdemand", alias, withAs);
	}

	public boolean isAutoGeneratedKeys() {
		return true;
	}

	public Class<BuildPubdemand> getPojoType() {
		return BuildPubdemand.class;
	}

}
