
package org.tinygroup.buildinfo.dao.inter.constant;

import org.tinygroup.buildinfo.dao.inter.pojo.BuildServicecontent;
import org.tinygroup.tinysqldsl.base.Column;
import org.tinygroup.tinysqldsl.base.Table;

/**
 * <!-- begin-user-doc --> 具体服务内容表 * <!-- end-user-doc -->
 */
public class BuildServicecontentTable extends Table {

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public static final BuildServicecontentTable BUILD_SERVICECONTENT_TABLE = new BuildServicecontentTable();

	/**
	 * <!-- begin-user-doc --> ID * <!-- end-user-doc -->
	 */
	public final Column ID = new Column(this, "id");
	/**
	 * <!-- begin-user-doc --> 所属服务 * <!-- end-user-doc -->
	 */
	public final Column SERVICE_CODE = new Column(this, "service_code");
	/**
	 * <!-- begin-user-doc --> 业务简介 * <!-- end-user-doc -->
	 */
	public final Column SERVICE_DES = new Column(this, "service_des");
	/**
	 * <!-- begin-user-doc --> 业务流程 * <!-- end-user-doc -->
	 */
	public final Column SERVICE_FLOW = new Column(this, "service_flow");
	/**
	 * <!-- begin-user-doc --> 所需资料 * <!-- end-user-doc -->
	 */
	public final Column SERVICE_DATA = new Column(this, "service_data");
	/**
	 * <!-- begin-user-doc --> 申请条件 * <!-- end-user-doc -->
	 */
	public final Column SERVICE_TERM = new Column(this, "service_term");
	/**
	 * <!-- begin-user-doc --> 扩展字段1 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_1 = new Column(this, "ext_field_1");
	/**
	 * <!-- begin-user-doc --> 扩展字段2 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_2 = new Column(this, "ext_field_2");
	/**
	 * <!-- begin-user-doc --> 扩展字段3 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_3 = new Column(this, "ext_field_3");
	/**
	 * <!-- begin-user-doc --> 扩展字段4 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_4 = new Column(this, "ext_field_4");
	/**
	 * <!-- begin-user-doc --> 扩展字段5 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_5 = new Column(this, "ext_field_5");

	public BuildServicecontentTable() {
		super("build_servicecontent");
	}

	public BuildServicecontentTable(String schemaName) {
		super(schemaName, "build_servicecontent");
	}

	public BuildServicecontentTable(String schemaName, String alias) {
		super(schemaName, "build_servicecontent", alias);
	}

	public BuildServicecontentTable(String schemaName, String alias, boolean withAs) {
		super(schemaName, "build_servicecontent", alias, withAs);
	}

	public boolean isAutoGeneratedKeys() {
		return true;
	}

	public Class<BuildServicecontent> getPojoType() {
		return BuildServicecontent.class;
	}

}
