
package org.tinygroup.buildinfo.dao.inter.constant;

import org.tinygroup.buildinfo.dao.inter.pojo.BuildRecruit;
import org.tinygroup.tinysqldsl.base.Column;
import org.tinygroup.tinysqldsl.base.Table;

/**
 * <!-- begin-user-doc --> 职位信息表 * <!-- end-user-doc -->
 */
public class BuildRecruitTable extends Table {

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public static final BuildRecruitTable BUILD_RECRUIT_TABLE = new BuildRecruitTable();

	/**
	 * <!-- begin-user-doc --> ID * <!-- end-user-doc -->
	 */
	public final Column ID = new Column(this, "id");
	/**
	 * <!-- begin-user-doc --> 职位名称 * <!-- end-user-doc -->
	 */
	public final Column RECRUIT_NAME = new Column(this, "recruit_name");
	/**
	 * <!-- begin-user-doc --> 招聘状态 * <!-- end-user-doc -->
	 */
	public final Column RECRUIT_STATE = new Column(this, "recruit_state");
	/**
	 * <!-- begin-user-doc --> 发布时间 * <!-- end-user-doc -->
	 */
	public final Column PUB_TIME = new Column(this, "pub_time");
	/**
	 * <!-- begin-user-doc --> 发布人 * <!-- end-user-doc -->
	 */
	public final Column PUB_USER = new Column(this, "pub_user");
	/**
	 * <!-- begin-user-doc --> 修改时间 * <!-- end-user-doc -->
	 */
	public final Column UPDATE_TIME = new Column(this, "update_time");
	/**
	 * <!-- begin-user-doc --> 更新人 * <!-- end-user-doc -->
	 */
	public final Column UPDATE_USER = new Column(this, "update_user");
	/**
	 * <!-- begin-user-doc --> 职位描述 * <!-- end-user-doc -->
	 */
	public final Column RECRUIT_DESC = new Column(this, "recruit_desc");
	/**
	 * <!-- begin-user-doc --> 任职职责 * <!-- end-user-doc -->
	 */
	public final Column RECRUIT_SENIORITY = new Column(this, "recruit_seniority");
	/**
	 * <!-- begin-user-doc --> 扩展字段 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD = new Column(this, "ext_field");

	public BuildRecruitTable() {
		super("build_recruit");
	}

	public BuildRecruitTable(String schemaName) {
		super(schemaName, "build_recruit");
	}

	public BuildRecruitTable(String schemaName, String alias) {
		super(schemaName, "build_recruit", alias);
	}

	public BuildRecruitTable(String schemaName, String alias, boolean withAs) {
		super(schemaName, "build_recruit", alias, withAs);
	}

	public boolean isAutoGeneratedKeys() {
		return true;
	}

	public Class<BuildRecruit> getPojoType() {
		return BuildRecruit.class;
	}

}
