
package org.tinygroup.buildinfo.dao.inter.constant;

import org.tinygroup.buildinfo.dao.inter.pojo.BuildAdisver;
import org.tinygroup.tinysqldsl.base.Column;
import org.tinygroup.tinysqldsl.base.Table;

/**
 * <!-- begin-user-doc --> 星级顾问 * <!-- end-user-doc -->
 */
public class BuildAdisverTable extends Table {

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public static final BuildAdisverTable BUILD_ADISVER_TABLE = new BuildAdisverTable();

	/**
	 * <!-- begin-user-doc --> ID * <!-- end-user-doc -->
	 */
	public final Column ID = new Column(this, "id");
	/**
	 * <!-- begin-user-doc --> NAME * <!-- end-user-doc -->
	 */
	public final Column NAME = new Column(this, "name");
	/**
	 * <!-- begin-user-doc --> 星级 * <!-- end-user-doc -->
	 */
	public final Column STARS = new Column(this, "stars");
	/**
	 * <!-- begin-user-doc --> 职业编号 * <!-- end-user-doc -->
	 */
	public final Column JOB_NUMBER = new Column(this, "job_number");
	/**
	 * <!-- begin-user-doc --> 工作年限 * <!-- end-user-doc -->
	 */
	public final Column WORK_YEARS = new Column(this, "work_years");
	/**
	 * <!-- begin-user-doc --> 顾问电话 * <!-- end-user-doc -->
	 */
	public final Column ADISVER_PHONE = new Column(this, "adisver_phone");
	/**
	 * <!-- begin-user-doc --> 个人简介 * <!-- end-user-doc -->
	 */
	public final Column ADISVER_RESUME = new Column(this, "adisver_resume");
	/**
	 * <!-- begin-user-doc --> 顾问头像 * <!-- end-user-doc -->
	 */
	public final Column ADISVER_IMG = new Column(this, "adisver_img");
	/**
	 * <!-- begin-user-doc --> 服务经验 * <!-- end-user-doc -->
	 */
	public final Column SERVICE_EXPERIENCE = new Column(this, "service_experience");
	/**
	 * <!-- begin-user-doc --> 服务类型 * <!-- end-user-doc -->
	 */
	public final Column SERVICE_TYPE = new Column(this, "service_type");
	/**
	 * <!-- begin-user-doc --> 扩展字段1 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_1 = new Column(this, "ext_field_1");
	/**
	 * <!-- begin-user-doc --> 扩展字段2 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_2 = new Column(this, "ext_field_2");
	/**
	 * <!-- begin-user-doc --> 扩展字段3 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_3 = new Column(this, "ext_field_3");
	/**
	 * <!-- begin-user-doc --> 扩展字段4 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_4 = new Column(this, "ext_field_4");
	/**
	 * <!-- begin-user-doc --> 扩展字段5 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_5 = new Column(this, "ext_field_5");

	public BuildAdisverTable() {
		super("build_adisver");
	}

	public BuildAdisverTable(String schemaName) {
		super(schemaName, "build_adisver");
	}

	public BuildAdisverTable(String schemaName, String alias) {
		super(schemaName, "build_adisver", alias);
	}

	public BuildAdisverTable(String schemaName, String alias, boolean withAs) {
		super(schemaName, "build_adisver", alias, withAs);
	}

	public boolean isAutoGeneratedKeys() {
		return true;
	}

	public Class<BuildAdisver> getPojoType() {
		return BuildAdisver.class;
	}

}
