
package org.tinygroup.buildinfo.dao.inter.constant;

import org.tinygroup.buildinfo.dao.inter.pojo.BuildNews;
import org.tinygroup.tinysqldsl.base.Column;
import org.tinygroup.tinysqldsl.base.Table;

/**
 * <!-- begin-user-doc --> 新闻动态 * <!-- end-user-doc -->
 */
public class BuildNewsTable extends Table {

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public static final BuildNewsTable BUILD_NEWS_TABLE = new BuildNewsTable();

	/**
	 * <!-- begin-user-doc --> ID * <!-- end-user-doc -->
	 */
	public final Column ID = new Column(this, "id");
	/**
	 * <!-- begin-user-doc --> 新闻标题 * <!-- end-user-doc -->
	 */
	public final Column NEWS_NAME = new Column(this, "news_name");
	/**
	 * <!-- begin-user-doc --> 发布时间 * <!-- end-user-doc -->
	 */
	public final Column PUB_DATE = new Column(this, "pub_date");
	
	public final Column NEWS_DESC = new Column(this, "news_desc");
	/**
	 * <!-- begin-user-doc --> 新闻类别 * <!-- end-user-doc -->
	 */
	public final Column NEWS_TYPE = new Column(this, "news_type");
	/**
	 * <!-- begin-user-doc --> 新闻内容 * <!-- end-user-doc -->
	 */
	public final Column NEWS_CONTENT = new Column(this, "news_content");
	/**
	 * <!-- begin-user-doc --> 是否热点新闻 * <!-- end-user-doc -->
	 */
	public final Column IS_HOT = new Column(this, "is_hot");
	/**
	 * <!-- begin-user-doc --> 新闻图片 * <!-- end-user-doc -->
	 */
	public final Column NEWS_IMG = new Column(this, "news_img");
	/**
	 * <!-- begin-user-doc --> 扩展字段1 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_1 = new Column(this, "ext_field_1");
	/**
	 * <!-- begin-user-doc --> 扩展字段2 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_2 = new Column(this, "ext_field_2");
	/**
	 * <!-- begin-user-doc --> 扩展字段3 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_3 = new Column(this, "ext_field_3");
	/**
	 * <!-- begin-user-doc --> 扩展字段4 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_4 = new Column(this, "ext_field_4");
	/**
	 * <!-- begin-user-doc --> 扩展字段5 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_5 = new Column(this, "ext_field_5");

	public BuildNewsTable() {
		super("build_news");
	}

	public BuildNewsTable(String schemaName) {
		super(schemaName, "build_news");
	}

	public BuildNewsTable(String schemaName, String alias) {
		super(schemaName, "build_news", alias);
	}

	public BuildNewsTable(String schemaName, String alias, boolean withAs) {
		super(schemaName, "build_news", alias, withAs);
	}

	public boolean isAutoGeneratedKeys() {
		return true;
	}

	public Class<BuildNews> getPojoType() {
		return BuildNews.class;
	}

}
