
package org.tinygroup.buildinfo.dao.inter.constant;

import org.tinygroup.buildinfo.dao.inter.pojo.BuildCustomercase;
import org.tinygroup.tinysqldsl.base.Column;
import org.tinygroup.tinysqldsl.base.Table;

/**
 * <!-- begin-user-doc --> 客户案例 * <!-- end-user-doc -->
 */
public class BuildCustomercaseTable extends Table {

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public static final BuildCustomercaseTable BUILD_CUSTOMERCASE_TABLE = new BuildCustomercaseTable();

	/**
	 * <!-- begin-user-doc --> ID * <!-- end-user-doc -->
	 */
	public final Column ID = new Column(this, "id");
	/**
	 * <!-- begin-user-doc --> 案例名称 * <!-- end-user-doc -->
	 */
	public final Column CASE_NAME = new Column(this, "case_name");
	/**
	 * <!-- begin-user-doc --> 发布时间 * <!-- end-user-doc -->
	 */
	public final Column PUB_DATE = new Column(this, "pub_date");
	/**
	 * <!-- begin-user-doc --> 案例详情 * <!-- end-user-doc -->
	 */
	public final Column CASE_INFORMATION = new Column(this, "case_information");
	/**
	 * <!-- begin-user-doc --> 案例图片 * <!-- end-user-doc -->
	 */
	public final Column CASE_IMG = new Column(this, "case_img");
	/**
	 * <!-- begin-user-doc --> 扩展字段1 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_1 = new Column(this, "ext_field_1");
	/**
	 * <!-- begin-user-doc --> 扩展字段2 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_2 = new Column(this, "ext_field_2");
	/**
	 * <!-- begin-user-doc --> 扩展字段3 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_3 = new Column(this, "ext_field_3");
	/**
	 * <!-- begin-user-doc --> 扩展字段4 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_4 = new Column(this, "ext_field_4");
	/**
	 * <!-- begin-user-doc --> 扩展字段5 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_5 = new Column(this, "ext_field_5");

	public BuildCustomercaseTable() {
		super("build_customercase");
	}

	public BuildCustomercaseTable(String schemaName) {
		super(schemaName, "build_customercase");
	}

	public BuildCustomercaseTable(String schemaName, String alias) {
		super(schemaName, "build_customercase", alias);
	}

	public BuildCustomercaseTable(String schemaName, String alias, boolean withAs) {
		super(schemaName, "build_customercase", alias, withAs);
	}

	public boolean isAutoGeneratedKeys() {
		return true;
	}

	public Class<BuildCustomercase> getPojoType() {
		return BuildCustomercase.class;
	}

}
