
package org.tinygroup.buildinfo.dao.inter.constant;

import org.tinygroup.buildinfo.dao.inter.pojo.BuildServicecenter;
import org.tinygroup.tinysqldsl.base.Column;
import org.tinygroup.tinysqldsl.base.Table;

/**
 * <!-- begin-user-doc --> 服务中心表 * <!-- end-user-doc -->
 */
public class BuildServicecenterTable extends Table {

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public static final BuildServicecenterTable BUILD_SERVICECENTER_TABLE = new BuildServicecenterTable();

	/**
	 * <!-- begin-user-doc --> ID * <!-- end-user-doc -->
	 */
	public final Column ID = new Column(this, "id");
	/**
	 * <!-- begin-user-doc --> 服务中心编码 * <!-- end-user-doc -->
	 */
	public final Column SERVICECENTER_CODE = new Column(this, "servicecenter_code");
	/**
	 * <!-- begin-user-doc --> 服务中心名称 * <!-- end-user-doc -->
	 */
	public final Column SERVICECENTER_NAME = new Column(this, "servicecenter_name");
	/**
	 * <!-- begin-user-doc --> 服务中心描述 * <!-- end-user-doc -->
	 */
	public final Column SERVICECENTER_DESC = new Column(this, "servicecenter_desc");
	/**
	 * <!-- begin-user-doc --> 扩展字段1 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_1 = new Column(this, "ext_field_1");
	/**
	 * <!-- begin-user-doc --> 扩展字段2 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_2 = new Column(this, "ext_field_2");
	/**
	 * <!-- begin-user-doc --> 扩展字段3 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_3 = new Column(this, "ext_field_3");
	/**
	 * <!-- begin-user-doc --> 扩展字段4 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_4 = new Column(this, "ext_field_4");
	/**
	 * <!-- begin-user-doc --> 扩展字段5 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_5 = new Column(this, "ext_field_5");

	public BuildServicecenterTable() {
		super("build_servicecenter");
	}

	public BuildServicecenterTable(String schemaName) {
		super(schemaName, "build_servicecenter");
	}

	public BuildServicecenterTable(String schemaName, String alias) {
		super(schemaName, "build_servicecenter", alias);
	}

	public BuildServicecenterTable(String schemaName, String alias, boolean withAs) {
		super(schemaName, "build_servicecenter", alias, withAs);
	}

	public boolean isAutoGeneratedKeys() {
		return true;
	}

	public Class<BuildServicecenter> getPojoType() {
		return BuildServicecenter.class;
	}

}
