
package org.tinygroup.buildinfo.dao.inter.constant;

import org.tinygroup.buildinfo.dao.inter.pojo.BuildServicetype;
import org.tinygroup.tinysqldsl.base.Column;
import org.tinygroup.tinysqldsl.base.Table;

/**
 * <!-- begin-user-doc --> 服务种类表 * <!-- end-user-doc -->
 */
public class BuildServicetypeTable extends Table {

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public static final BuildServicetypeTable BUILD_SERVICETYPE_TABLE = new BuildServicetypeTable();

	/**
	 * <!-- begin-user-doc --> ID * <!-- end-user-doc -->
	 */
	public final Column ID = new Column(this, "id");
	
	public final Column SERVICE_CODE = new Column(this, "service_code");
	/**
	 * <!-- begin-user-doc --> 服务名称 * <!-- end-user-doc -->
	 */
	public final Column SERVICE_NAME = new Column(this, "service_name");
	/**
	 * <!-- begin-user-doc --> 服务大类 * <!-- end-user-doc -->
	 */
	public final Column PARENT_SERVICE = new Column(this, "parent_service");
	/**
	 * <!-- begin-user-doc --> 服务图标* <!-- end-user-doc -->
	 */
	public final Column SERVICE_ICON = new Column(this, "service_icon");
	/**
	 * <!-- begin-user-doc --> 备注 * <!-- end-user-doc -->
	 */
	public final Column REMARK = new Column(this, "remark");
	/**
	 * <!-- begin-user-doc --> 扩展字段1 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_1 = new Column(this, "ext_field_1");
	/**
	 * <!-- begin-user-doc --> 扩展字段2 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_2 = new Column(this, "ext_field_2");
	/**
	 * <!-- begin-user-doc --> 扩展字段3 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_3 = new Column(this, "ext_field_3");
	/**
	 * <!-- begin-user-doc --> 扩展字段4 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_4 = new Column(this, "ext_field_4");
	/**
	 * <!-- begin-user-doc --> 扩展字段5 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_5 = new Column(this, "ext_field_5");

	public BuildServicetypeTable() {
		super("build_servicetype");
	}

	public BuildServicetypeTable(String schemaName) {
		super(schemaName, "build_servicetype");
	}

	public BuildServicetypeTable(String schemaName, String alias) {
		super(schemaName, "build_servicetype", alias);
	}

	public BuildServicetypeTable(String schemaName, String alias, boolean withAs) {
		super(schemaName, "build_servicetype", alias, withAs);
	}

	public boolean isAutoGeneratedKeys() {
		return true;
	}

	public Class<BuildServicetype> getPojoType() {
		return BuildServicetype.class;
	}

}
