/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.buildinfo.dao.inter.constant;

import org.tinygroup.tinysqldsl.base.Column;
import org.tinygroup.tinysqldsl.base.Table;

/**
 * <!-- begin-user-doc --> 错误代码表 * <!-- end-user-doc -->
 */
public class TberrormsgTable extends Table {

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public static final TberrormsgTable TBERRORMSG_TABLE = new TberrormsgTable();

	/**
	 * <!-- begin-user-doc --> ID * <!-- end-user-doc -->
	 */
	public final Column ID = new Column(this, "id");
	/**
	 * <!-- begin-user-doc --> 执行结果 * <!-- end-user-doc -->
	 */
	public final Column ERR_CODE = new Column(this, "err_code");
	/**
	 * <!-- begin-user-doc --> 执行结果信息 * <!-- end-user-doc -->
	 */
	public final Column ERR_MSG = new Column(this, "err_msg");

	public TberrormsgTable() {
		super("tberrormsg");
	}

	public boolean isAutoGeneratedKeys() {
		return true;
	}
}
