/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.buildinfo.dao.inter.constant;

import org.tinygroup.tinysqldsl.base.Column;
import org.tinygroup.tinysqldsl.base.Table;

/**
 * <!-- begin-user-doc --> 用户历史密码表 * <!-- end-user-doc -->
 */
public class TbhisuerpwdTable extends Table {

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public static final TbhisuerpwdTable TBHISUERPWD_TABLE = new TbhisuerpwdTable();

	/**
	 * <!-- begin-user-doc --> 流水号 * <!-- end-user-doc -->
	 */
	public final Column SERIAL_NO = new Column(this, "serial_no");
	/**
	 * <!-- begin-user-doc --> 用户代码 * <!-- end-user-doc -->
	 */
	public final Column USER_ID = new Column(this, "user_id");
	/**
	 * <!-- begin-user-doc --> 用户密码 * <!-- end-user-doc -->
	 */
	public final Column USER_PWD = new Column(this, "user_pwd");
	/**
	 * <!-- begin-user-doc --> 备用1 * <!-- end-user-doc -->
	 */
	public final Column RESERVE1 = new Column(this, "reserve1");
	/**
	 * <!-- begin-user-doc --> ID * <!-- end-user-doc -->
	 */
	public final Column ID = new Column(this, "id");

	public TbhisuerpwdTable() {
		super("tbhisuerpwd");
	}

	public boolean isAutoGeneratedKeys() {
		return true;
	}
}
