package org.tinygroup.buildinfo.dao.inter.constant;

import org.tinygroup.buildinfo.dao.inter.pojo.Tbparam;
import org.tinygroup.tinysqldsl.base.Column;
import org.tinygroup.tinysqldsl.base.Table;

/**
 * <!-- begin-user-doc --> 参数配置表 * <!-- end-user-doc -->
 */
public class TbparamTable extends Table {

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public static final TbparamTable TBPARAM_TABLE = new TbparamTable();

	/**
	 * <!-- begin-user-doc --> ID * <!-- end-user-doc -->
	 */
	public final Column ID = new Column(this, "id");
	/**
	 * <!-- begin-user-doc --> 分类标识代码 * <!-- end-user-doc -->
	 */
	public final Column TA_CODE = new Column(this, "ta_code");
	/**
	 * <!-- begin-user-doc --> PARAM_ID * <!-- end-user-doc -->
	 */
	public final Column PARAM_ID = new Column(this, "param_id");
	/**
	 * <!-- begin-user-doc --> 参数标识名称 * <!-- end-user-doc -->
	 */
	public final Column PARAM_NAME = new Column(this, "param_name");
	/**
	 * <!-- begin-user-doc --> 参数值 * <!-- end-user-doc -->
	 */
	public final Column PARAM_VALUE = new Column(this, "param_value");
	/**
	 * <!-- begin-user-doc --> 参数名称 * <!-- end-user-doc -->
	 */
	public final Column VALUE_NAME = new Column(this, "value_name");
	/**
	 * <!-- begin-user-doc --> 归属系统 * <!-- end-user-doc -->
	 */
	public final Column BELONG_TYPE = new Column(this, "belong_type");
	/**
	 * <!-- begin-user-doc --> 允许修改标志 * <!-- end-user-doc -->
	 */
	public final Column MODI_FLAG = new Column(this, "modi_flag");
	/**
	 * <!-- begin-user-doc --> 备用1 * <!-- end-user-doc -->
	 */
	public final Column RESERVE1 = new Column(this, "reserve1");

	public TbparamTable() {
		super("tbparam");
	}

	public boolean isAutoGeneratedKeys() {
		return true;
	}

	public Class<Tbparam> getPojoType() {
		return Tbparam.class;
	}

}

