/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.buildinfo.dao.inter.constant;

import org.tinygroup.buildinfo.dao.inter.pojo.Tbtrans;
import org.tinygroup.tinysqldsl.base.Column;
import org.tinygroup.tinysqldsl.base.Table;

/**
 * <!-- begin-user-doc --> 交易配置表 * <!-- end-user-doc -->
 */
public class TbtransTable extends Table {

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public static final TbtransTable TBTRANS_TABLE = new TbtransTable();

	/**
	 * <!-- begin-user-doc --> ID * <!-- end-user-doc -->
	 */
	public final Column ID = new Column(this, "id");
	/**
	 * <!-- begin-user-doc --> 交易编号 * <!-- end-user-doc -->
	 */
	public final Column TRANS_CODE = new Column(this, "trans_code");
	/**
	 * <!-- begin-user-doc --> 交易名称 * <!-- end-user-doc -->
	 */
	public final Column TRANS_NAME = new Column(this, "trans_name");
	/**
	 * <!-- begin-user-doc --> 交易允许 * <!-- end-user-doc -->
	 */
	public final Column ENABLE_FLAG = new Column(this, "enable_flag");
	/**
	 * <!-- begin-user-doc --> 允许渠道组 * <!-- end-user-doc -->
	 */
	public final Column CHANNELS = new Column(this, "channels");
	/**
	 * <!-- begin-user-doc --> 后台联机 * <!-- end-user-doc -->
	 */
	public final Column HOST_ONLINE = new Column(this, "host_online");
	/**
	 * <!-- begin-user-doc --> 交易类别 * <!-- end-user-doc -->
	 */
	public final Column TRANS_TYPE = new Column(this, "trans_type");
	/**
	 * <!-- begin-user-doc --> 监控标志 * <!-- end-user-doc -->
	 */
	public final Column MONITOR_STATUS = new Column(this, "monitor_status");
	/**
	 * <!-- begin-user-doc --> 日志级别 * <!-- end-user-doc -->
	 */
	public final Column LOG_LEVEL = new Column(this, "log_level");
	/**
	 * <!-- begin-user-doc --> 监控交易类别 * <!-- end-user-doc -->
	 */
	public final Column MON_TRANS_TYPE = new Column(this, "mon_trans_type");
	/**
	 * <!-- begin-user-doc --> 备用1 * <!-- end-user-doc -->
	 */
	public final Column RESERVE1 = new Column(this, "reserve1");
	/**
	 * <!-- begin-user-doc --> 备注2 * <!-- end-user-doc -->
	 */
	public final Column RESERVE2 = new Column(this, "reserve2");
	/**
	 * <!-- begin-user-doc --> 保留域3 * <!-- end-user-doc -->
	 */
	public final Column RESERVE3 = new Column(this, "reserve3");

	public TbtransTable() {
		super("tbtrans");
	}

	public boolean isAutoGeneratedKeys() {
		return true;
	}

	public Class<Tbtrans> getPojoType() {
		return Tbtrans.class;
	}
}
