/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.buildinfo.dao.inter.constant;

import org.tinygroup.tinysqldsl.base.Column;
import org.tinygroup.tinysqldsl.base.Table;

/**
 * <!-- begin-user-doc --> 角色权限授权表 * <!-- end-user-doc -->
 */
public class TsysRoleRightTable extends Table {

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public static final TsysRoleRightTable TSYS_ROLE_RIGHT_TABLE = new TsysRoleRightTable();

	/**
	 * <!-- begin-user-doc --> ID * <!-- end-user-doc -->
	 */
	public final Column ID = new Column(this, "id");
	/**
	 * <!-- begin-user-doc --> 角色编号 * <!-- end-user-doc -->
	 */
	public final Column ROLE_CODE = new Column(this, "role_code");
	
	public final Column MENU_ID = new Column(this, "menu_id");
	/**
	 * <!-- begin-user-doc --> 分配人 * <!-- end-user-doc -->
	 */
	public final Column CREATE_BY = new Column(this, "create_by");
	/**
	 * <!-- begin-user-doc --> 创建时间 * <!-- end-user-doc -->
	 */
	public final Column CREATE_DATE = new Column(this, "create_date");
	/**
	 * <!-- begin-user-doc --> 开始时间 * <!-- end-user-doc -->
	 */
	public final Column BEGIN_DATE = new Column(this, "begin_date");
	/**
	 * <!-- begin-user-doc --> 截止时间 * <!-- end-user-doc -->
	 */
	public final Column END_DATE = new Column(this, "end_date");
	/**
	 * <!-- begin-user-doc --> 授权标志 * <!-- end-user-doc -->
	 */
	public final Column RIGHT_FLAG = new Column(this, "right_flag");

	public TsysRoleRightTable() {
		super("tsys_role_right");
	}

	public boolean isAutoGeneratedKeys() {
		return true;
	}
}
