/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.buildinfo.dao.inter.constant;

import org.tinygroup.tinysqldsl.base.Column;
import org.tinygroup.tinysqldsl.base.Table;

/**
 * <!-- begin-user-doc --> 字典条目表 * <!-- end-user-doc -->
 */
public class TsysDictEntryTable extends Table {

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public static final TsysDictEntryTable TSYS_DICT_ENTRY_TABLE = new TsysDictEntryTable();

	/**
	 * <!-- begin-user-doc --> ID * <!-- end-user-doc -->
	 */
	public final Column ID = new Column(this, "id");
	/**
	 * <!-- begin-user-doc --> 字典条目编号 * <!-- end-user-doc -->
	 */
	public final Column DICT_ENTRY_CODE = new Column(this, "dict_entry_code");
	/**
	 * <!-- begin-user-doc --> 分类编号 * <!-- end-user-doc -->
	 */
	public final Column KIND_CODE = new Column(this, "kind_code");
	/**
	 * <!-- begin-user-doc --> 字典条目名称 * <!-- end-user-doc -->
	 */
	public final Column DICT_ENTRY_NAME = new Column(this, "dict_entry_name");
	/**
	 * <!-- begin-user-doc --> 控制标志 * <!-- end-user-doc -->
	 */
	public final Column CTRL_FLAG = new Column(this, "ctrl_flag");
	/**
	 * <!-- begin-user-doc --> 备注 * <!-- end-user-doc -->
	 */
	public final Column REMARK = new Column(this, "remark");

	public TsysDictEntryTable() {
		super("tsys_dict_entry");
	}

	public boolean isAutoGeneratedKeys() {
		return true;
	}
}
