/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.buildinfo.dao.inter.constant;

import org.tinygroup.tinysqldsl.base.Column;
import org.tinygroup.tinysqldsl.base.Table;

/**
 * <!-- begin-user-doc --> 系统菜单表 * <!-- end-user-doc -->
 */
public class TsysMenuTable extends Table {

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public static final TsysMenuTable TSYS_MENU_TABLE = new TsysMenuTable();

	/**
	 * <!-- begin-user-doc --> ID * <!-- end-user-doc -->
	 */
	public final Column ID = new Column(this, "menu_id");
	/**
	 * <!-- begin-user-doc --> 菜单编号 * <!-- end-user-doc -->
	 */
	public final Column MENU_CODE = new Column(this, "menu_code");
	/**
	 * <!-- begin-user-doc --> 分类编号 * <!-- end-user-doc -->
	 */
	public final Column KIND_CODE = new Column(this, "kind_code");
	/**
	 * <!-- begin-user-doc --> 菜单名称 * <!-- end-user-doc -->
	 */
	public final Column MENU_NAME = new Column(this, "menu_name");
	/**
	 * <!-- begin-user-doc --> 菜单参数 * <!-- end-user-doc -->
	 */
	public final Column MENU_ARG = new Column(this, "menu_arg");
	/**
	 * <!-- begin-user-doc --> 菜单图标 * <!-- end-user-doc -->
	 */
	public final Column MENU_ICON = new Column(this, "menu_icon");
	/**
	 * <!-- begin-user-doc --> 窗口类型 * <!-- end-user-doc -->
	 */
	public final Column WINDOW_TYPE = new Column(this, "window_type");
	/**
	 * <!-- begin-user-doc --> 提示信息 * <!-- end-user-doc -->
	 */
	public final Column TIP = new Column(this, "tip");
	/**
	 * <!-- begin-user-doc --> 快捷键 * <!-- end-user-doc -->
	 */
	public final Column HOT_KEY = new Column(this, "hot_key");
	
	/**
	 * <!-- begin-user-doc --> 上级 * <!-- end-user-doc -->
	 */
	public final Column PARENT_ID = new Column(this, "parent_id");
	/**
	 * <!-- begin-user-doc --> 序号 * <!-- end-user-doc -->
	 */
	public final Column ORDER_NO = new Column(this, "order_no");
	/**
	 * <!-- begin-user-doc --> 展开标志 * <!-- end-user-doc -->
	 */
	public final Column OPEN_FLAG = new Column(this, "open_flag");
	/**
	 * <!-- begin-user-doc --> 树索引码 * <!-- end-user-doc -->
	 */
	public final Column TREE_IDX = new Column(this, "tree_idx");
	/**
	 * <!-- begin-user-doc --> 备注 * <!-- end-user-doc -->
	 */
	public final Column REMARK = new Column(this, "remark");
	/**
	 * <!-- begin-user-doc --> 窗口模式 * <!-- end-user-doc -->
	 */
	public final Column WINDOW_MODEL = new Column(this, "window_model");
	/**
	 * <!-- begin-user-doc --> 菜单URL * <!-- end-user-doc -->
	 */
	public final Column MENU_URL = new Column(this, "menu_url");

	public TsysMenuTable() {
		super("tsys_menu");
	}

	public boolean isAutoGeneratedKeys() {
		return true;
	}
}
