/**
 *  Copyright (c) 1997-2013, www.tinygroup.org (luo_guo@icloud.com).
 *
 *  Licensed under the GPL, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.gnu.org/licenses/gpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.tinygroup.buildinfo.dao.inter.constant;

import org.tinygroup.tinysqldsl.base.Column;
import org.tinygroup.tinysqldsl.base.Table;

/**
 * <!-- begin-user-doc --> 字典项表 * <!-- end-user-doc -->
 */
public class TsysDictItemTable extends Table {

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public static final TsysDictItemTable TSYS_DICT_ITEM_TABLE = new TsysDictItemTable();

	/**
	 * <!-- begin-user-doc --> ID * <!-- end-user-doc -->
	 */
	public final Column ID = new Column(this, "id");
	/**
	 * <!-- begin-user-doc --> 字典项编号 * <!-- end-user-doc -->
	 */
	public final Column DICT_ITEM_CODE = new Column(this, "dict_item_code");
	/**
	 * <!-- begin-user-doc --> 字典条目编号 * <!-- end-user-doc -->
	 */
	public final Column DICT_ENTRY_CODE = new Column(this, "dict_entry_code");
	/**
	 * <!-- begin-user-doc --> 字典项名称 * <!-- end-user-doc -->
	 */
	public final Column DICT_ITEM_NAME = new Column(this, "dict_item_name");
	/**
	 * <!-- begin-user-doc --> 字典项排序 * <!-- end-user-doc -->
	 */
	public final Column DICT_ITEM_ORDER = new Column(this, "dict_item_order");
	/**
	 * <!-- begin-user-doc --> 字典条目ID * <!-- end-user-doc -->
	 */
	public final Column DICT_ENTRY_ID = new Column(this, "dict_entry_id");

	public TsysDictItemTable() {
		super("tsys_dict_item");
	}

	public boolean isAutoGeneratedKeys() {
		return true;
	}
}
