
package org.tinygroup.workplan.dao.inter.constant;

import org.tinygroup.tinysqldsl.base.Column;
import org.tinygroup.tinysqldsl.base.Table;
import org.tinygroup.workplan.dao.inter.pojo.TUserTask;

/**
 * <!-- begin-user-doc --> 人员任务表 * <!-- end-user-doc -->
 */
public class TUserTaskTable extends Table {

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public static final TUserTaskTable T_USER_TASK_TABLE = new TUserTaskTable();

	/**
	 * <!-- begin-user-doc --> ID * <!-- end-user-doc -->
	 */
	public final Column ID = new Column(this, "id");
	/**
	 * <!-- begin-user-doc --> 关联编号 * <!-- end-user-doc -->
	 */
	public final Column LINE_ID = new Column(this, "line_id");
	/**
	 * <!-- begin-user-doc --> 任务类别 * <!-- end-user-doc -->
	 */
	public final Column TASK_TYPE = new Column(this, "task_type");
	/**
	 * <!-- begin-user-doc --> 创建人员 * <!-- end-user-doc -->
	 */
	public final Column CREATE_USER = new Column(this, "create_user");
	/**
	 * <!-- begin-user-doc --> 责任人 * <!-- end-user-doc -->
	 */
	public final Column DUTY_USER = new Column(this, "duty_user");
	/**
	 * <!-- begin-user-doc --> 扩展字段1 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_1 = new Column(this, "ext_field_1");
	/**
	 * <!-- begin-user-doc --> 扩展字段2 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_2 = new Column(this, "ext_field_2");
	/**
	 * <!-- begin-user-doc --> 扩展字段3 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_3 = new Column(this, "ext_field_3");
	/**
	 * <!-- begin-user-doc --> 扩展字段4 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_4 = new Column(this, "ext_field_4");
	/**
	 * <!-- begin-user-doc --> 扩展字段5 * <!-- end-user-doc -->
	 */
	public final Column EXT_FIELD_5 = new Column(this, "ext_field_5");

	public TUserTaskTable() {
		super("t_user_task");
	}

	public TUserTaskTable(String schemaName) {
		super(schemaName, "t_user_task");
	}

	public TUserTaskTable(String schemaName, String alias) {
		super(schemaName, "t_user_task", alias);
	}

	public TUserTaskTable(String schemaName, String alias, boolean withAs) {
		super(schemaName, "t_user_task", alias, withAs);
	}

	public boolean isAutoGeneratedKeys() {
		return true;
	}

	public Class<TUserTask> getPojoType() {
		return TUserTask.class;
	}

}
